# decoder.yaml
_target_: CatalystGen.modules.decoder.GemNetTDecoder
hidden_dim: 128
latent_dim: ${model.latent_dim}
max_neighbors: ${model.max_neighbors}
radius: ${model.radius}
scale_file: CatalystGen/modules/gemnet/gemnet-dT.json

